### ISSUE TITLE
Interested in 4th team member?

### ISSUE THREAD

**Issue by rothfels** [scalableinternetservices/swap-space#6]
There are a few students without a project group looking for a team to join. Are you interested in having a 4th team member? My records indicate you are currently a team of 3.

**Comment by GalenWong** [comment]
@rothfels
Hi John, yes, we are currently looking for a 4th team member. Since one of our previous team member was on the waitlist and she couldn't get into the class. It would be great if we can get a 4th member!

**Comment by cheimu** [comment]
Hi, Could I join your team? I'm a first year master in CS and currently don't have any group :D

**Comment by GalenWong** [comment]
@cheimu Sure, no problem. Can we find you on facebook? We have a messenger chat set up and I can add you to the group. 

All of our members attend discussion 1A, which is the one from 12-2pm. Please let me know if you can make it to that session.

**Comment by cheimu** [comment]
Sure, my facebook is just my name, Gaohong Liu, and I think I can switch to discussion 1A. See you tomorrow.

**Comment by GalenWong** [comment]
@cheimu I just sent you a friend request on Facebook (Galen Wong). Please let me know if you can't see it.
